Updating examples to work with release changes.
Still need to test on windows.

diff --git a/examples/mail_report b/examples/mail_report
--- a/examples/mail_report
+++ b/examples/mail_report
@@ -20,13 +20,7 @@ EMAIL_ADDRESS=$EMAIL
 # you can get member_id and platform from dclim
 # (here it pulls from environment but you can also hardcode)
 MEMBER_ID=$MEMBER_ID
-
 PLATFORM=$PLATFORM
-
-# character_id to retrieve stats for
-# can retrieve character_ids from dclic
-# (here it pulls from environment but you can also hardcode)
-CHARACTER_ID=$CHARACTER_ID
 
 # modes to generate a report for. options include: all, control, 
 # clash, mayhem, ironbanner, private, rumble, comp, quickplay 
@@ -74,16 +68,16 @@ for mode in "${MODES[@]}"; do
     OUTPUT+="************************************************************************************************************\n"
 
     #2>&1 this redirects stderr to stdout so we can capture
-    TMP_OUTPUT=$(dclics --member-id "$MEMBER_ID" --character-id "$CHARACTER_ID" --platform "$PLATFORM" --mode "$mode" --moment week 2>&1)
+    TMP_OUTPUT=$(dcliah --member-id "$MEMBER_ID" --platform "$PLATFORM" --class all --mode "$mode" --moment week 2> /dev/null)
 
     if [ $? -eq 1 ] 
     then
         echo "${TMP_OUTPUT}">&2 #redirect to stderr
-        echo -e "\nError running dclics (see output above). Aborting. Exit code received from command [$?]">&2 #redirect to stderr
+        echo -e "\nError running dcliah (see output above). Aborting. Exit code received from command [$?]">&2 #redirect to stderr
         exit 1
     fi
 
-    if [ "${TMP_OUTPUT}" == "No results found." ]
+    if [ "${TMP_OUTPUT}" == "No activities found" ]
     then
         OUTPUT+="No games played"
         OUTPUT+="\n"
@@ -110,9 +104,6 @@ echo "Emailing report to: ${EMAIL_ADDRESS}"
 
 #just wrap in <pre>, so it maintains formatting from dclics output
 BODY="Mime-Version: 1.0\nContent-Type: text/html\n<html><body><pre style=\"font-family: monospace; font-size:medium;\">${OUTPUT}</pre></body></html>"
-
-#mail -s "${SUBJECT}" $EMAIL_ADDRESS <<< "${BODY}"
-#echo -e "$BODY"
 
 (echo "To: ${EMAIL_ADDRESS}"
     echo "Subject: ${SUBJECT}"
